services:
  music-manager-frontend:
    build:
      context: .
      args:
        VITE_API_HOST: ${VITE_API_HOST}
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - music-manager-backend
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network
      - backend-network
  
  music-manager-backend:
    image: dmytrolesyk/music-manager-backend:latest
    ports:
      - '8000:8000'
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
    name: music-manager-frontend
  backend-network:
    driver: bridge
    name: music-manager-backend

volumes:
  ssl-certs:
