name: Security Audit

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # Run security audit daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      run_snyk_scan:
        description: 'Run Snyk vulnerability scan'
        required: false
        default: false
        type: boolean

jobs:
  dependency-audit:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        
      - name: Run pnpm audit
        run: |
          echo "Running pnpm audit..."
          pnpm audit --audit-level moderate
          echo "✅ pnpm audit completed"
        
      - name: Run pnpm audit with JSON output
        run: |
          echo "Generating detailed audit report..."
          pnpm audit --json > audit-report.json || true
          
      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: security-audit-report
          path: audit-report.json
          retention-days: 30

  snyk-scan:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_snyk_scan == 'true'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          
      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-vulnerability-report
          path: snyk-report.json
          retention-days: 30